name: testing
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo ${{ vars.HAI }}
        env:
          TEST: ${{ vars.TEST }}
