name: testing
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: testing
        run: echo ${{ vars.HAI }}
        env:
          TEST: ${{ vars.TEST }}
      - name: testing secrets
        run: |
          echo "${{ secrets.TEST }}" >> file_test.txt &&\
          ls -lh && cat file_test.txt
      - name: Test libvirt
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
